### ISSUE TITLE
Error: Can not find Squirrel

### ISSUE THREAD

**Issue by wildone** [electron/update-electron-app#118]
Thank you for this marvellous tech!

I have added this module to my project but still getting an error.

Do we need to package using Squirrel.Windows? 

I am trying this now, this was not mentioned anywhere but it seem to be what other people are saying.

Here is my project details.

Release Repo: https://github.com/typerefinery-ai/typerefinery/releases

Implementation (index.ts)
```

import updateElectronApp from "update-electron-app"

if (!isDev) {
  // run auto update
  updateElectronApp({
    repo: "typerefinery-ai/typerefinery",
    updateInterval: "1 hour",
  })
}

```

Error:

```
[2023-07-04 13:19:07.162] [info]  updater error
[2023-07-04 13:19:07.163] [info]  Error: Can not find Squirrel
    at AutoUpdater.checkForUpdates (node:electron/js2c/browser_init:2:3709)
    at initUpdater (C:\Users\maxbarrass\AppData\Local\Programs\TypeRefinery\resources\app.asar\node_modules\update-electron-app\index.js:92:15)
    at App.<anonymous> (C:\Users\maxbarrass\AppData\Local\Programs\TypeRefinery\resources\app.asar\node_modules\update-electron-app\index.js:33:43)
    at App.emit (node:events:525:35)
    at App.emit (node:domain:489:12)
    at emitter.emit (C:\Users\maxbarrass\AppData\Local\Programs\TypeRefinery\resources\app.asar\node_modules\@sentry\electron\main\integrations\electron-breadcrumbs.js:121:20)
```

**Comment by Droutin** [comment]
I have same problem

**Comment by erickzhao** [comment]
Hi, sorry this took so long to get a reply!

> Do we need to package using Squirrel.Windows?

The answer is yes, since that's what the `autoUpdater` module looks for under the hood in Electron. I think we could make this clearer in the README.
