### ISSUE TITLE
[ERR_ASSERTION]: host must be a valid HTTPS URL when using ElectronPublicUpdateService

### ISSUE THREAD

**Issue by fttx** [electron/update-electron-app#155]
This code:

```typescript
updateElectronApp({
    updateSource: {
        type: UpdateSourceType.ElectronPublicUpdateService,
        repo: 'owner/repo',
    },
})
```
is causing this error:

```
Uncaught Exception:
AssertionError [ERR_ASSERTION]: host must be a valid HTTPS URL
at validateInput (/myapp/electron/dist/mac-arm64/myapp.app/Contents/Resources/app.asar/node_modules/update-electron-app/dist/index.js:141:34)
at updateElectronApp (/myapp/electron/dist/mac-arm64/myapp.app/Contents/Resources/app.asar/node_modules/update-electron-app/dist/index.js:26:22)
at UpdateHandler.doUpdate (/myapp/electron/dist/mac-arm64/myapp.app/Contents/Resources/app.asar/bin/handlers/update.handler.js:53:9)
at IpcMainImpl.<anonymous> (/myapp/electron/dist/mac-arm64/myapp.app/Contents/Resources/app.asar/bin/handlers/update.handler.js:32:60)
at IpcMainImpl.emit (events.js:376:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
at Object.emit (events.js:376:20)
```

That means that it is failing to set the default value for the host parameter, in fact, when setting it to `host: "https://update.electronjs.org"` it goes away.

**Comment by Bug-Reaper** [comment]
@fttx Thanks for making an issue, just bumped into this and got stuck! 

Do you know if it matters what website the host is? Trying to figure out what is the purpose of a host-url is when we're just pointing at a GH repo?
